# Generated by Django 6.0.3 on 2026-03-23 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_rename_todo_task_alter_task_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(blank=True, choices=[('Work', 'Work'), ('Personal', 'Personal'), ('Urgent', 'Urgent'), ('Long-term', 'Long-term')], max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='prioritize',
            field=models.CharField(blank=True, choices=[('High', 'urgent'), ('Medium', 'important but not urgent'), ('Low', 'optional')], max_length=100),
        ),
    ]
